# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from QcomboBox import ComboCheckBox
provinces = ["北京市","天津市","河北省","山西省","内蒙古自治区","辽宁省","吉林省","黑龙江省","上海市","江苏省","浙江省","安徽省","福建省",
             "江西省","山东省","河南省","湖北省","湖南省","广东省","广西壮族自治区","海南省","重庆市","四川省","贵州省","云南省","西藏自治区",
             "陕西省","甘肃省","青海省","宁夏回族自治区","新疆维吾尔自治区","香港特别行政区","澳门特别行政区","台湾省"]
class Ui_zhuwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1777, 1446)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table1.setGeometry(QtCore.QRect(310, 220, 951, 361))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(6)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(740, 130, 221, 41))
        self.label.setMinimumSize(QtCore.QSize(221, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setAutoFillBackground(False)
        self.label.setObjectName("label")
        self.history = QtWidgets.QPushButton(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(290, 660, 221, 151))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.history.setFont(font)
        self.history.setObjectName("history")
        self.dangerQ = QtWidgets.QPushButton(self.centralwidget)
        self.dangerQ.setGeometry(QtCore.QRect(290, 910, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dangerQ.setFont(font)
        self.dangerQ.setObjectName("dangerQ")
        self.PatientQ = QtWidgets.QPushButton(self.centralwidget)
        self.PatientQ.setGeometry(QtCore.QRect(630, 660, 241, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.PatientQ.setFont(font)
        self.PatientQ.setObjectName("PatientQ")
        self.dangerI = QtWidgets.QPushButton(self.centralwidget)
        self.dangerI.setGeometry(QtCore.QRect(630, 910, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dangerI.setFont(font)
        self.dangerI.setObjectName("dangerI")
        self.PatientE = QtWidgets.QPushButton(self.centralwidget)
        self.PatientE.setGeometry(QtCore.QRect(640, 1140, 231, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.PatientE.setFont(font)
        self.PatientE.setObjectName("PatientE")
        self.Auth = QtWidgets.QPushButton(self.centralwidget)
        self.Auth.setGeometry(QtCore.QRect(960, 670, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Auth.setFont(font)
        self.Auth.setObjectName("Auth")
        self.dangerQ_2 = QtWidgets.QPushButton(self.centralwidget)
        self.dangerQ_2.setGeometry(QtCore.QRect(290, 1130, 231, 141))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.dangerQ_2.setFont(font)
        self.dangerQ_2.setObjectName("dangerQ_2")
        self.Subp = QtWidgets.QPushButton(self.centralwidget)
        self.Subp.setGeometry(QtCore.QRect(460, 140, 241, 51))
        self.Subp.setObjectName("Subp")
        self.Wholep = QtWidgets.QPushButton(self.centralwidget)
        self.Wholep.setGeometry(QtCore.QRect(1040, 140, 131, 51))
        self.Wholep.setObjectName("Wholep")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1777, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Interface"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "省份"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "累计确诊"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "现有确诊"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "治愈患者"))
        item = self.table1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "疑似病例"))
        item = self.table1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "死亡人数"))
        self.label.setText(_translate("MainWindow", "订阅省份结果"))
        self.history.setText(_translate("MainWindow", "历史数据查询"))
        self.dangerQ.setText(_translate("MainWindow", "危险车次查询"))
        self.PatientQ.setText(_translate("MainWindow", "患者查询（管理员）"))
        self.dangerI.setText(_translate("MainWindow", "危险车次编辑"))
        self.PatientE.setText(_translate("MainWindow", "患者信息编辑"))
        self.Auth.setText(_translate("MainWindow", "授权管理"))
        self.dangerQ_2.setText(_translate("MainWindow", "订阅"))
        self.Subp.setText(_translate("MainWindow", "显示订阅省份（无订阅则全国）"))
        self.Wholep.setText(_translate("MainWindow", "显示全国"))
class Ui_SubWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1231, 1064)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 40, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 160, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 100, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(170, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 230, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(170, 420, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(170, 290, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(170, 350, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 630, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 560, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 860, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(170, 780, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(170, 710, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(370, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(370, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(370, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(370, 230, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(370, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(370, 420, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(370, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(370, 560, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(370, 490, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(370, 710, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(370, 630, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(370, 860, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(370, 780, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(520, 40, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(520, 100, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(520, 160, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(520, 230, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(520, 290, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(520, 360, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(520, 430, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(520, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.c1 = QtWidgets.QCheckBox(self.centralwidget)
        self.c1.setGeometry(QtCore.QRect(100, 60, 31, 23))
        self.c1.setText("")
        self.c1.setObjectName("c1")
        self.c2 = QtWidgets.QCheckBox(self.centralwidget)
        self.c2.setGeometry(QtCore.QRect(100, 110, 31, 23))
        self.c2.setText("")
        self.c2.setObjectName("c2")
        self.c3 = QtWidgets.QCheckBox(self.centralwidget)
        self.c3.setGeometry(QtCore.QRect(100, 170, 31, 23))
        self.c3.setText("")
        self.c3.setObjectName("c3")
        self.c4 = QtWidgets.QCheckBox(self.centralwidget)
        self.c4.setGeometry(QtCore.QRect(100, 240, 31, 23))
        self.c4.setText("")
        self.c4.setObjectName("c4")
        self.c5 = QtWidgets.QCheckBox(self.centralwidget)
        self.c5.setGeometry(QtCore.QRect(100, 310, 31, 23))
        self.c5.setText("")
        self.c5.setObjectName("c5")
        self.c6 = QtWidgets.QCheckBox(self.centralwidget)
        self.c6.setGeometry(QtCore.QRect(100, 360, 31, 23))
        self.c6.setText("")
        self.c6.setObjectName("c6")
        self.c7 = QtWidgets.QCheckBox(self.centralwidget)
        self.c7.setGeometry(QtCore.QRect(100, 430, 31, 23))
        self.c7.setText("")
        self.c7.setObjectName("c7")
        self.c8 = QtWidgets.QCheckBox(self.centralwidget)
        self.c8.setGeometry(QtCore.QRect(110, 500, 31, 23))
        self.c8.setText("")
        self.c8.setObjectName("c8")
        self.c9 = QtWidgets.QCheckBox(self.centralwidget)
        self.c9.setGeometry(QtCore.QRect(110, 560, 31, 23))
        self.c9.setText("")
        self.c9.setObjectName("c9")
        self.c10 = QtWidgets.QCheckBox(self.centralwidget)
        self.c10.setGeometry(QtCore.QRect(110, 640, 31, 23))
        self.c10.setText("")
        self.c10.setObjectName("c10")
        self.c11 = QtWidgets.QCheckBox(self.centralwidget)
        self.c11.setGeometry(QtCore.QRect(110, 720, 31, 23))
        self.c11.setText("")
        self.c11.setObjectName("c11")
        self.c12 = QtWidgets.QCheckBox(self.centralwidget)
        self.c12.setGeometry(QtCore.QRect(110, 790, 31, 23))
        self.c12.setText("")
        self.c12.setObjectName("c12")
        self.c13 = QtWidgets.QCheckBox(self.centralwidget)
        self.c13.setGeometry(QtCore.QRect(110, 870, 31, 23))
        self.c13.setText("")
        self.c13.setObjectName("c13")
        self.c14 = QtWidgets.QCheckBox(self.centralwidget)
        self.c14.setGeometry(QtCore.QRect(310, 50, 31, 23))
        self.c14.setText("")
        self.c14.setObjectName("c14")
        self.c15 = QtWidgets.QCheckBox(self.centralwidget)
        self.c15.setGeometry(QtCore.QRect(310, 100, 31, 23))
        self.c15.setText("")
        self.c15.setObjectName("c15")
        self.c16 = QtWidgets.QCheckBox(self.centralwidget)
        self.c16.setGeometry(QtCore.QRect(310, 170, 31, 23))
        self.c16.setText("")
        self.c16.setObjectName("c16")
        self.c17 = QtWidgets.QCheckBox(self.centralwidget)
        self.c17.setGeometry(QtCore.QRect(310, 230, 31, 23))
        self.c17.setText("")
        self.c17.setObjectName("c17")
        self.c18 = QtWidgets.QCheckBox(self.centralwidget)
        self.c18.setGeometry(QtCore.QRect(310, 290, 31, 23))
        self.c18.setText("")
        self.c18.setObjectName("c18")
        self.c19 = QtWidgets.QCheckBox(self.centralwidget)
        self.c19.setGeometry(QtCore.QRect(310, 360, 31, 23))
        self.c19.setText("")
        self.c19.setObjectName("c19")
        self.c20 = QtWidgets.QCheckBox(self.centralwidget)
        self.c20.setGeometry(QtCore.QRect(310, 430, 31, 23))
        self.c20.setText("")
        self.c20.setObjectName("c20")
        self.c21 = QtWidgets.QCheckBox(self.centralwidget)
        self.c21.setGeometry(QtCore.QRect(310, 500, 31, 23))
        self.c21.setText("")
        self.c21.setObjectName("c21")
        self.c22 = QtWidgets.QCheckBox(self.centralwidget)
        self.c22.setGeometry(QtCore.QRect(310, 560, 31, 23))
        self.c22.setText("")
        self.c22.setObjectName("c22")
        self.c23 = QtWidgets.QCheckBox(self.centralwidget)
        self.c23.setGeometry(QtCore.QRect(310, 630, 31, 23))
        self.c23.setText("")
        self.c23.setObjectName("c23")
        self.c24 = QtWidgets.QCheckBox(self.centralwidget)
        self.c24.setGeometry(QtCore.QRect(310, 710, 31, 23))
        self.c24.setText("")
        self.c24.setObjectName("c24")
        self.c25 = QtWidgets.QCheckBox(self.centralwidget)
        self.c25.setGeometry(QtCore.QRect(310, 790, 31, 23))
        self.c25.setText("")
        self.c25.setObjectName("c25")
        self.c26 = QtWidgets.QCheckBox(self.centralwidget)
        self.c26.setGeometry(QtCore.QRect(310, 870, 31, 23))
        self.c26.setText("")
        self.c26.setObjectName("c26")
        self.c27 = QtWidgets.QCheckBox(self.centralwidget)
        self.c27.setGeometry(QtCore.QRect(480, 50, 31, 23))
        self.c27.setText("")
        self.c27.setObjectName("c27")
        self.c28 = QtWidgets.QCheckBox(self.centralwidget)
        self.c28.setGeometry(QtCore.QRect(480, 110, 31, 23))
        self.c28.setText("")
        self.c28.setObjectName("c28")
        self.c29 = QtWidgets.QCheckBox(self.centralwidget)
        self.c29.setGeometry(QtCore.QRect(480, 170, 31, 23))
        self.c29.setText("")
        self.c29.setObjectName("c29")
        self.c30 = QtWidgets.QCheckBox(self.centralwidget)
        self.c30.setGeometry(QtCore.QRect(480, 230, 31, 23))
        self.c30.setText("")
        self.c30.setObjectName("c30")
        self.c31 = QtWidgets.QCheckBox(self.centralwidget)
        self.c31.setGeometry(QtCore.QRect(480, 290, 31, 23))
        self.c31.setText("")
        self.c31.setObjectName("c31")
        self.c32 = QtWidgets.QCheckBox(self.centralwidget)
        self.c32.setGeometry(QtCore.QRect(480, 370, 31, 23))
        self.c32.setText("")
        self.c32.setObjectName("c32")
        self.c33 = QtWidgets.QCheckBox(self.centralwidget)
        self.c33.setGeometry(QtCore.QRect(480, 440, 31, 23))
        self.c33.setText("")
        self.c33.setObjectName("c33")
        self.c34 = QtWidgets.QCheckBox(self.centralwidget)
        self.c34.setGeometry(QtCore.QRect(480, 510, 31, 23))
        self.c34.setText("")
        self.c34.setObjectName("c34")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 200, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(800, 70, 281, 81))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(860, 380, 191, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1231, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "订阅"))
        self.label.setText(_translate("MainWindow", "北京市"))
        self.label_2.setText(_translate("MainWindow", "河北省"))
        self.label_3.setText(_translate("MainWindow", "天津市"))
        self.label_4.setText(_translate("MainWindow", "黑龙江省"))
        self.label_5.setText(_translate("MainWindow", "山西省"))
        self.label_6.setText(_translate("MainWindow", "吉林省"))
        self.label_7.setText(_translate("MainWindow", "内蒙古"))
        self.label_8.setText(_translate("MainWindow", "辽宁省"))
        self.label_9.setText(_translate("MainWindow", "江苏省"))
        self.label_10.setText(_translate("MainWindow", "上海市"))
        self.label_11.setText(_translate("MainWindow", "福建省"))
        self.label_12.setText(_translate("MainWindow", "安徽省"))
        self.label_13.setText(_translate("MainWindow", "浙江省"))
        self.label_14.setText(_translate("MainWindow", "山东省"))
        self.label_15.setText(_translate("MainWindow", "江西省"))
        self.label_16.setText(_translate("MainWindow", "河南省"))
        self.label_17.setText(_translate("MainWindow", "湖北省"))
        self.label_18.setText(_translate("MainWindow", "湖南省"))
        self.label_19.setText(_translate("MainWindow", "广西省"))
        self.label_20.setText(_translate("MainWindow", "广东省"))
        self.label_21.setText(_translate("MainWindow", "重庆市"))
        self.label_22.setText(_translate("MainWindow", "海南省"))
        self.label_23.setText(_translate("MainWindow", "贵州省"))
        self.label_24.setText(_translate("MainWindow", "四川省"))
        self.label_25.setText(_translate("MainWindow", "西藏"))
        self.label_26.setText(_translate("MainWindow", "云南省"))
        self.label_27.setText(_translate("MainWindow", "陕西省"))
        self.label_28.setText(_translate("MainWindow", "甘肃省"))
        self.label_29.setText(_translate("MainWindow", "青海省"))
        self.label_30.setText(_translate("MainWindow", "宁夏"))
        self.label_31.setText(_translate("MainWindow", "新疆"))
        self.label_32.setText(_translate("MainWindow", "香港"))
        self.label_33.setText(_translate("MainWindow", "澳门"))
        self.label_34.setText(_translate("MainWindow", "台湾"))
        self.pushButton.setText(_translate("MainWindow", "订阅"))
        self.label_35.setText(_translate("MainWindow", "请勾选需要订阅的省份"))
        self.label_36.setText(_translate("MainWindow", "订阅成功！"))

class Ui_DangerEWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1393, 1202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(170, 511, 961, 481))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tab1 = QtWidgets.QTabWidget(self.centralwidget)
        self.tab1.setGeometry(QtCore.QRect(170, 130, 961, 301))
        self.tab1.setObjectName("tab1")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(80, 60, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.insert1 = QtWidgets.QLineEdit(self.tab)
        self.insert1.setGeometry(QtCore.QRect(270, 80, 311, 41))
        self.insert1.setObjectName("insert1")
        self.insert2 = QtWidgets.QDateEdit(self.tab)
        self.insert2.setGeometry(QtCore.QRect(270, 170, 121, 41))
        self.insert2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.insert2.setObjectName("insert2")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(650, 90, 191, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tab1.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(80, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.insert1_2 = QtWidgets.QLineEdit(self.tab_2)
        self.insert1_2.setGeometry(QtCore.QRect(270, 80, 311, 41))
        self.insert1_2.setObjectName("insert1_2")
        self.insert2_2 = QtWidgets.QDateEdit(self.tab_2)
        self.insert2_2.setGeometry(QtCore.QRect(270, 170, 121, 41))
        self.insert2_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.insert2_2.setObjectName("insert2_2")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(80, 60, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(650, 90, 191, 101))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.tab1.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.insert1_4 = QtWidgets.QLineEdit(self.tab_3)
        self.insert1_4.setGeometry(QtCore.QRect(700, 80, 201, 41))
        self.insert1_4.setObjectName("insert1_4")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(510, 60, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(510, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.insert2_4 = QtWidgets.QDateEdit(self.tab_3)
        self.insert2_4.setGeometry(QtCore.QRect(700, 170, 121, 41))
        self.insert2_4.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.insert2_4.setObjectName("insert2_4")
        self.insert1_5 = QtWidgets.QLineEdit(self.tab_3)
        self.insert1_5.setGeometry(QtCore.QRect(230, 80, 201, 41))
        self.insert1_5.setText("")
        self.insert1_5.setObjectName("insert1_5")
        self.insert2_5 = QtWidgets.QDateEdit(self.tab_3)
        self.insert2_5.setGeometry(QtCore.QRect(230, 170, 121, 41))
        self.insert2_5.setDateTime(QtCore.QDateTime(QtCore.QDate(2020, 1, 1), QtCore.QTime(0, 0, 0)))
        self.insert2_5.setObjectName("insert2_5")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(40, 160, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(40, 70, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 220, 112, 34))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.tab1.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1393, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab1.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "危险车次编辑"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Traffic_id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "车次日期"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "车次编号"))
        self.label.setText(_translate("MainWindow", "车次编号"))
        self.label_2.setText(_translate("MainWindow", "车次日期"))
        self.pushButton.setText(_translate("MainWindow", "添加"))
        self.tab1.setTabText(self.tab1.indexOf(self.tab), _translate("MainWindow", "增加"))
        self.label_3.setText(_translate("MainWindow", "车次日期"))
        self.label_4.setText(_translate("MainWindow", "车次编号"))
        self.pushButton_2.setText(_translate("MainWindow", "删除"))
        self.tab1.setTabText(self.tab1.indexOf(self.tab_2), _translate("MainWindow", "删除"))
        self.label_8.setText(_translate("MainWindow", "改后编号"))
        self.label_7.setText(_translate("MainWindow", "改后日期"))
        self.label_5.setText(_translate("MainWindow", "改前日期"))
        self.label_6.setText(_translate("MainWindow", "改前编号"))
        self.pushButton_3.setText(_translate("MainWindow", "修改"))
        self.tab1.setTabText(self.tab1.indexOf(self.tab_3), _translate("MainWindow", "修改"))

class Ui_DangerQuery(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 852)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 170, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 400, 261, 131))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.number = QtWidgets.QLineEdit(self.centralwidget)
        self.number.setGeometry(QtCore.QRect(420, 200, 511, 71))
        self.number.setObjectName("number")
        self.button1 = QtWidgets.QPushButton(self.centralwidget)
        self.button1.setGeometry(QtCore.QRect(430, 590, 301, 91))
        self.button1.setObjectName("button1")
        self.date = QtWidgets.QDateEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(420, 430, 341, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.date.setFont(font)
        self.date.setDate(QtCore.QDate(2020, 1, 1))
        self.date.setObjectName("date")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "危险车次查询"))
        self.label.setText(_translate("MainWindow", "请输入车次编号"))
        self.label_2.setText(_translate("MainWindow", "请输入日期"))
        self.button1.setText(_translate("MainWindow", "查询"))


class Ui_shouquan(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1261, 1025)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(170, 130, 871, 421))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.button1 = QtWidgets.QPushButton(self.tab)
        self.button1.setGeometry(QtCore.QRect(320, 260, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button1.setFont(font)
        self.button1.setObjectName("button1")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(140, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(140, 160, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.id1 = QtWidgets.QLineEdit(self.tab)
        self.id1.setGeometry(QtCore.QRect(290, 120, 351, 41))
        self.id1.setObjectName("id1")
        self.xiala1 = QtWidgets.QComboBox(self.tab)
        self.xiala1.setGeometry(QtCore.QRect(290, 180, 321, 31))
        self.xiala1.setObjectName("xiala1")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.xiala1.addItem("")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(140, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.xiala2 = QtWidgets.QComboBox(self.tab_2)
        self.xiala2.setGeometry(QtCore.QRect(290, 180, 321, 31))
        self.xiala2.setObjectName("xiala2")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(140, 160, 111, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.id2 = QtWidgets.QLineEdit(self.tab_2)
        self.id2.setGeometry(QtCore.QRect(290, 120, 351, 41))
        self.id2.setObjectName("id2")
        self.button2 = QtWidgets.QPushButton(self.tab_2)
        self.button2.setGeometry(QtCore.QRect(320, 260, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button2.setFont(font)
        self.button2.setObjectName("button2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.id2_3 = QtWidgets.QLineEdit(self.tab_3)
        self.id2_3.setGeometry(QtCore.QRect(290, 120, 351, 41))
        self.id2_3.setObjectName("id2_3")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(140, 100, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.button2_3 = QtWidgets.QPushButton(self.tab_3)
        self.button2_3.setGeometry(QtCore.QRect(320, 260, 201, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.button2_3.setFont(font)
        self.button2_3.setObjectName("button2_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.table1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table1.setGeometry(QtCore.QRect(170, 590, 891, 301))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(5)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(4, item)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 590, 112, 34))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1261, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "授权管理"))
        self.button1.setText(_translate("MainWindow", "添加"))
        self.label.setText(_translate("MainWindow", "用户id"))
        self.label_2.setText(_translate("MainWindow", "授权省份"))
        self.xiala1.setItemText(0, _translate("MainWindow", "北京市"))
        self.xiala1.setItemText(1, _translate("MainWindow", "天津市"))
        self.xiala1.setItemText(2, _translate("MainWindow", "河北省"))
        self.xiala1.setItemText(3, _translate("MainWindow", "山西省"))
        self.xiala1.setItemText(4, _translate("MainWindow", "内蒙古自治区"))
        self.xiala1.setItemText(5, _translate("MainWindow", "辽宁省"))
        self.xiala1.setItemText(6, _translate("MainWindow", "吉林省"))
        self.xiala1.setItemText(7, _translate("MainWindow", "黑龙江省"))
        self.xiala1.setItemText(8, _translate("MainWindow", "上海市"))
        self.xiala1.setItemText(9, _translate("MainWindow", "江苏省"))
        self.xiala1.setItemText(10, _translate("MainWindow", "浙江省"))
        self.xiala1.setItemText(11, _translate("MainWindow", "安徽省"))
        self.xiala1.setItemText(12, _translate("MainWindow", "福建省"))
        self.xiala1.setItemText(13, _translate("MainWindow", "江西省"))
        self.xiala1.setItemText(14, _translate("MainWindow", "山东省"))
        self.xiala1.setItemText(15, _translate("MainWindow", "河南省"))
        self.xiala1.setItemText(16, _translate("MainWindow", "湖北省"))
        self.xiala1.setItemText(17, _translate("MainWindow", "湖南省"))
        self.xiala1.setItemText(18, _translate("MainWindow", "广东省"))
        self.xiala1.setItemText(19, _translate("MainWindow", "广西壮族自治区"))
        self.xiala1.setItemText(20, _translate("MainWindow", "海南省"))
        self.xiala1.setItemText(21, _translate("MainWindow", "重庆市"))
        self.xiala1.setItemText(22, _translate("MainWindow", "四川省"))
        self.xiala1.setItemText(23, _translate("MainWindow", "贵州省"))
        self.xiala1.setItemText(24, _translate("MainWindow", "云南省"))
        self.xiala1.setItemText(25, _translate("MainWindow", "西藏自治区"))
        self.xiala1.setItemText(26, _translate("MainWindow", "陕西省"))
        self.xiala1.setItemText(27, _translate("MainWindow", "甘肃省"))
        self.xiala1.setItemText(28, _translate("MainWindow", "青海省"))
        self.xiala1.setItemText(29, _translate("MainWindow", "宁夏回族自治区"))
        self.xiala1.setItemText(30, _translate("MainWindow", "新疆维吾尔自治区"))
        self.xiala1.setItemText(31, _translate("MainWindow", "香港特别行政区"))
        self.xiala1.setItemText(32, _translate("MainWindow", "澳门特别行政区"))
        self.xiala1.setItemText(33, _translate("MainWindow", "台湾省"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "添加授权"))
        self.label_3.setText(_translate("MainWindow", "用户id"))
        self.xiala2.setItemText(0, _translate("MainWindow", "北京市"))
        self.xiala2.setItemText(1, _translate("MainWindow", "天津市"))
        self.xiala2.setItemText(2, _translate("MainWindow", "河北省"))
        self.xiala2.setItemText(3, _translate("MainWindow", "山西省"))
        self.xiala2.setItemText(4, _translate("MainWindow", "内蒙古自治区"))
        self.xiala2.setItemText(5, _translate("MainWindow", "辽宁省"))
        self.xiala2.setItemText(6, _translate("MainWindow", "吉林省"))
        self.xiala2.setItemText(7, _translate("MainWindow", "黑龙江省"))
        self.xiala2.setItemText(8, _translate("MainWindow", "上海市"))
        self.xiala2.setItemText(9, _translate("MainWindow", "江苏省"))
        self.xiala2.setItemText(10, _translate("MainWindow", "浙江省"))
        self.xiala2.setItemText(11, _translate("MainWindow", "安徽省"))
        self.xiala2.setItemText(12, _translate("MainWindow", "福建省"))
        self.xiala2.setItemText(13, _translate("MainWindow", "江西省"))
        self.xiala2.setItemText(14, _translate("MainWindow", "山东省"))
        self.xiala2.setItemText(15, _translate("MainWindow", "河南省"))
        self.xiala2.setItemText(16, _translate("MainWindow", "湖北省"))
        self.xiala2.setItemText(17, _translate("MainWindow", "湖南省"))
        self.xiala2.setItemText(18, _translate("MainWindow", "广东省"))
        self.xiala2.setItemText(19, _translate("MainWindow", "广西壮族自治区"))
        self.xiala2.setItemText(20, _translate("MainWindow", "海南省"))
        self.xiala2.setItemText(21, _translate("MainWindow", "重庆市"))
        self.xiala2.setItemText(22, _translate("MainWindow", "四川省"))
        self.xiala2.setItemText(23, _translate("MainWindow", "贵州省"))
        self.xiala2.setItemText(24, _translate("MainWindow", "云南省"))
        self.xiala2.setItemText(25, _translate("MainWindow", "西藏自治区"))
        self.xiala2.setItemText(26, _translate("MainWindow", "陕西省"))
        self.xiala2.setItemText(27, _translate("MainWindow", "甘肃省"))
        self.xiala2.setItemText(28, _translate("MainWindow", "青海省"))
        self.xiala2.setItemText(29, _translate("MainWindow", "宁夏回族自治区"))
        self.xiala2.setItemText(30, _translate("MainWindow", "新疆维吾尔自治区"))
        self.xiala2.setItemText(31, _translate("MainWindow", "香港特别行政区"))
        self.xiala2.setItemText(32, _translate("MainWindow", "澳门特别行政区"))
        self.xiala2.setItemText(33, _translate("MainWindow", "台湾省"))
        self.label_4.setText(_translate("MainWindow", "授权省份"))
        self.button2.setText(_translate("MainWindow", "删除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "删除授权"))
        self.label_9.setText(_translate("MainWindow", "用户id"))
        self.button2_3.setText(_translate("MainWindow", "废除"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "废为庶人"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "用户id"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "用户名"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "授权省份id"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "授权省份名称"))
        item = self.table1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "授权类型"))
        self.pushButton.setText(_translate("MainWindow", "刷新"))

class Ui_history(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1317, 979)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table1 = QtWidgets.QTableWidget(self.centralwidget)
        self.table1.setGeometry(QtCore.QRect(110, 430, 1111, 421))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(7)
        self.table1.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(6, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 110, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.xiala2 = QtWidgets.QComboBox(self.centralwidget)
        self.xiala2.setGeometry(QtCore.QRect(430, 110, 371, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.xiala2.setFont(font)
        self.xiala2.setObjectName("xiala2")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.xiala2.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(270, 230, 71, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.date1 = QtWidgets.QDateEdit(self.centralwidget)
        self.date1.setGeometry(QtCore.QRect(480, 240, 151, 51))
        self.date1.setDate(QtCore.QDate(2020, 1, 1))
        self.date1.setObjectName("date1")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(730, 240, 151, 51))
        self.dateEdit_2.setDate(QtCore.QDate(2020, 12, 31))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(400, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(970, 140, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1317, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "省份"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "日期"))
        item = self.table1.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "患者总数"))
        item = self.table1.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "治愈人数"))
        item = self.table1.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "现有确诊"))
        item = self.table1.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "疑似病例"))
        item = self.table1.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "死亡人数"))
        self.label.setText(_translate("MainWindow", "省份"))
        self.xiala2.setItemText(0, _translate("MainWindow", "北京市"))
        self.xiala2.setItemText(1, _translate("MainWindow", "天津市"))
        self.xiala2.setItemText(2, _translate("MainWindow", "河北省"))
        self.xiala2.setItemText(3, _translate("MainWindow", "山西省"))
        self.xiala2.setItemText(4, _translate("MainWindow", "内蒙古自治区"))
        self.xiala2.setItemText(5, _translate("MainWindow", "辽宁省"))
        self.xiala2.setItemText(6, _translate("MainWindow", "吉林省"))
        self.xiala2.setItemText(7, _translate("MainWindow", "黑龙江省"))
        self.xiala2.setItemText(8, _translate("MainWindow", "上海市"))
        self.xiala2.setItemText(9, _translate("MainWindow", "江苏省"))
        self.xiala2.setItemText(10, _translate("MainWindow", "浙江省"))
        self.xiala2.setItemText(11, _translate("MainWindow", "安徽省"))
        self.xiala2.setItemText(12, _translate("MainWindow", "福建省"))
        self.xiala2.setItemText(13, _translate("MainWindow", "江西省"))
        self.xiala2.setItemText(14, _translate("MainWindow", "山东省"))
        self.xiala2.setItemText(15, _translate("MainWindow", "河南省"))
        self.xiala2.setItemText(16, _translate("MainWindow", "湖北省"))
        self.xiala2.setItemText(17, _translate("MainWindow", "湖南省"))
        self.xiala2.setItemText(18, _translate("MainWindow", "广东省"))
        self.xiala2.setItemText(19, _translate("MainWindow", "广西壮族自治区"))
        self.xiala2.setItemText(20, _translate("MainWindow", "海南省"))
        self.xiala2.setItemText(21, _translate("MainWindow", "重庆市"))
        self.xiala2.setItemText(22, _translate("MainWindow", "四川省"))
        self.xiala2.setItemText(23, _translate("MainWindow", "贵州省"))
        self.xiala2.setItemText(24, _translate("MainWindow", "云南省"))
        self.xiala2.setItemText(25, _translate("MainWindow", "西藏自治区"))
        self.xiala2.setItemText(26, _translate("MainWindow", "陕西省"))
        self.xiala2.setItemText(27, _translate("MainWindow", "甘肃省"))
        self.xiala2.setItemText(28, _translate("MainWindow", "青海省"))
        self.xiala2.setItemText(29, _translate("MainWindow", "宁夏回族自治区"))
        self.xiala2.setItemText(30, _translate("MainWindow", "新疆维吾尔自治区"))
        self.xiala2.setItemText(31, _translate("MainWindow", "香港特别行政区"))
        self.xiala2.setItemText(32, _translate("MainWindow", "澳门特别行政区"))
        self.xiala2.setItemText(33, _translate("MainWindow", "台湾省"))
        self.label_2.setText(_translate("MainWindow", "日期"))
        self.label_3.setText(_translate("MainWindow", "From"))
        self.label_4.setText(_translate("MainWindow", "To"))
        self.pushButton.setText(_translate("MainWindow", "查询"))

class Ui_PatientQ(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1499, 1170)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(130, 100, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 100, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 210, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 240, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(620, 240, 68, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(390, 220, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit.setFont(font)
        self.dateEdit.setDate(QtCore.QDate(1900, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_2.setGeometry(QtCore.QRect(700, 220, 201, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1060, 210, 131, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(150, 420, 1161, 541))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(670, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(1060, 100, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox = ComboCheckBox(self.centralwidget,provinces)
        self.comboBox.setGeometry(QtCore.QRect(810, 100, 191, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = ComboCheckBox(self.centralwidget,["1","2","3","4"])
        self.comboBox_2.setGeometry(QtCore.QRect(1210, 100, 191, 51))
        self.comboBox_2.setObjectName("comboBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1499, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox.setText(_translate("MainWindow", "患者姓名"))
        self.label.setText(_translate("MainWindow", "患者生日"))
        self.label_2.setText(_translate("MainWindow", "From"))
        self.label_3.setText(_translate("MainWindow", "To"))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "患者id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "患者姓名"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "患者身份证号"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "患者省份"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "患者生日"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "患者状态"))
        self.label_4.setText(_translate("MainWindow", "患者省份"))
        self.label_5.setText(_translate("MainWindow", "患者状态"))